### ISSUE TITLE
process-compose depends on global bash

### ISSUE THREAD

**Issue by srid** [Platonic-Systems/process-compose-flake#19]
On a pristine nixosTest VM, running a process-compose configuration can fail as follows:

```
vm-test-run-process-compose-default-test> 23-06-13 17:22:05.760 INF Process Compose v0.45.0
vm-test-run-process-compose-default-test> 23-06-13 17:22:05.761 INF start http server listening :8080
vm-test-run-process-compose-default-test> 23-06-13 17:22:05.762 INF Global shell command: bash -c
vm-test-run-process-compose-default-test> 23-06-13 17:22:05.762 FTL Couldn't find bash
```

**Comment by adrian-gierakowski** [comment]
Does it happen even if [shell](https://github.com/adrian-gierakowski/nix-microservice-monorepo/blob/13be2b41537838bc92c211e8977cd09abb49b687/nix/modules/process-compose-config-options.nix#L209) is set to a nix store path?

**Comment by srid** [comment]
Yup it works! Interesting. So I guess I should revert c206414e7ddfabca17e6a11be36f11460e6a9b68
