### ISSUE TITLE
Duplicate process-compose config schema as Nix submodules

### ISSUE THREAD

**Issue by marijanp** [Platonic-Systems/process-compose-flake#2]
- improves documentation
- makes the usage fool-proof

**Comment by srid** [comment]
I think we should do this in some fashion (submoduleWith or deferredModule) in order to be able to share process-compose-flake configs across flakes and to be able to `import` them, à la:

```nix
{
  process-compose.configs.demo = {
    imports = [ inputs.postgres-app.processComposeConfigs.default ];
    processes.myapp.command = "...";
  };
}
```

**Comment by adrian-gierakowski** [comment]
Feel free to still the schema from [here](https://github.com/adrian-gierakowski/nix-microservice-monorepo/blob/master/nix/modules/process-compose-config-options.nix). The only thing it’s missing is descriptions.
