### ISSUE TITLE
Suggstion: Wrap process groups in different output

### ISSUE THREAD

**Issue by MrFoxPro** [Platonic-Systems/process-compose-flake#26]
I think using 
```nix
devenv.shells.default = {
  packages = attrValues config.process-compose;
}
```
Could be more convenient then explicitly specifying packages.

**Comment by srid** [comment]
@MrFoxPro I don't understand. What exactly is it that you want process-compose-flake to support?

**Comment by MrFoxPro** [comment]
I mean can `process-compose-flake` produce its output to custom property? For example, deploy-rs produces ouptut to `config.deploy.nodes.*`, not in `config.packages.*`. 

My suggestion is make `process-compose-flake` produce output to non-standard flake output. Not sure how to deal with ${system} btw.

**Comment by srid** [comment]
It already exposes the output in `config.process-compose.<name>.package` https://flake.parts/options/process-compose-flake.html#opt-perSystem.process-compose.package

For manual wiring (overriding the auto wiring), we need #27

That should satisfy your use-case I think.

**Comment by MrFoxPro** [comment]
Wow, nice, didn't notice. Thank you very much for explaining and this tool.

**Comment by MrFoxPro** [comment]
> It already exposes the output in `config.process-compose.<name>.package` https://flake.parts/options/process-compose-flake.html#opt-perSystem.process-compose.package
> 
> For manual wiring (overriding the auto wiring), we need #27
> 
> That should satisfy your use-case I think.

Hm.
`config.process-compose."build:deno".package` doesn't work when specifiyng in packages
and `config.packages."build:deno"`- works.

**Comment by MrFoxPro** [comment]
Well, this works: `(map (item: item.outputs.package) (attrValues config.process-compose))`
