### ISSUE TITLE
process-compose hangs when running tailwind JIT

### ISSUE THREAD

**Issue by srid** [Platonic-Systems/process-compose-flake#30]
Honcho (via https://github.com/srid/proc-flake) can run it fine though.

I think this is an upstream bug, but filing an issue here for reference.

**Comment by thenonameguy** [comment]
Workaround to make it work with process-compose:
https://github.com/F1bonacc1/process-compose/issues/64#issuecomment-1793548454

**Comment by thenonameguy** [comment]
This is fixed now using `is_tty: true` with the latest release:
https://github.com/F1bonacc1/process-compose/commit/1eba53f748ea5379a1233bc86b4e7b57ce4d17f2
