### ISSUE TITLE
provide package which runs process-compose with --port only, for executing commands other than up

### ISSUE THREAD

**Issue by adrian-gierakowski** [Platonic-Systems/process-compose-flake#34]
the `--port` flag is the only global one which can be set for all sub-commands and its required by most when using non-standard port

To allow running sub-commands like: `process list|log` a package should be provided which simply calls `process-compose` with `--port` (if non-standard one is used). 

I've implemented it on my fork: https://github.com/rhinofi/process-compose/commit/ac789e4f9cb77cf7509a535908c962ec3d87ed85

Happy to submit a PR, and if desired adapt the above to keep default package unchanged and call the new one `${name}-base` or something (suggestions welcome).

**Comment by srid** [comment]
Can't we unify the two such that the single wrapper script deals with CLI arguments more sanely than process-compose does?

**Comment by adrian-gierakowski** [comment]
actually I think using `PC_DISABLE_TUI` and `PC_CONFIG_FILES`  env vars would complicated and require less maintenance

since invoking `process-compose` without subcommand defaults to `up`  we could have a single wrapper looking more or less like this:

```
PC_DISABLE_TUI=${!config.tui} PC_CONFIG_FILES=${config.file} process-compose "${@}"
```

**Comment by adrian-gierakowski** [comment]
happy to submit a PR

**Comment by srid** [comment]
Cool, I'd accept that as a PR.
